### ISSUE TITLE
roles.dict fails if no argument arg is given

### ISSUE THREAD

**Issue by kutschkem** [khrisrichardson/salt-states#11]
I saw you added a shiny new feature for defining roles on the command line, however, this is what happens now when you don't:

            An exception occurred in this state: Traceback (most recent call last):
              File "/usr/lib/python2.6/site-packages/salt/state.py", line 1563, in call
                **cdata['kwargs'])
              File "/var/cache/salt/minion/extmods/states/cloudera_cluster.py", line 52, in present
                if __salt__['cloudera.cluster_exists'](name, **cm_args):
              File "/var/cache/salt/minion/extmods/modules/cloudera.py", line 102, in cluster_exists
                a = _connect(**cm_args)
              File "/var/cache/salt/minion/extmods/modules/cloudera.py", line 79, in _connect
                a = ApiResource(__salt__['roles.dict']('cloudera-cm5-server')['cloudera-cm5-server'][0],
              File "/var/cache/salt/minion/extmods/modules/roles.py", line 80, in dict_
                kwargs = dict([i.split('=', 1)[:2] for i in __opts__['arg'] if '=' in i])
            KeyError: u'arg'

**Comment by khrisrichardson** [comment]
I tested this with 2014.7. Are you using 2015.5 by any chance?

**Comment by kutschkem** [comment]
Version of what? Salt?
